name: .NET CI/CD SimpleMapper


on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release --no-restore